### ISSUE TITLE
Produce design shortlist

### ISSUE THREAD

**Issue by slargman** [FECTeamOne/Atelier#9]
There are a few general patterns I noticed and which we could choose to follow as a paradigm. I also included some other sites (adidas, ZARA, and Opening Ceremony) which don't fall into these categories and show other options.

### Simple designs
These are pretty basic and minimalistic in their styling. A good option if we want to keep things very clean and simple.
- Goodfight
- Chivichivi

### Two panel block designs
Have a design where the product image takes up one half of the screen and the description takes up the other half. Superfluid uses some pretty interesting animations and it's worth taking a look at their site
- Superfluid
- JACQUEMUS
- Won Hundred

### Designs with borders
Greater use of borders to separate sections. Balenciaga also does this, but to an even greater degree.
- Senteurs d' Ailleurs
- Unrun

### Full width image
Product image takes up the full width of the screen with the description super imposed. Might not work as well with the kinds of product images we'll have.
- PHAEDIS

**Comment by slargman** [comment]
### Base Visual Design

**Overview**
![Screen Shot 2022-05-18 at 4 02 38 PM](https://user-images.githubusercontent.com/16127198/169169222-d3c0698f-b3c6-401a-8639-e0ac34dffefe.png)

**Ratings & Reviews**
![Screen Shot 2022-05-18 at 4 01 27 PM](https://user-images.githubusercontent.com/16127198/169169244-03bb5745-f98a-429d-a4b7-e8f3362f5d3e.png)

**Questions & Answers**
![Screen Shot 2022-05-18 at 4 02 48 PM](https://user-images.githubusercontent.com/16127198/169169261-7f642f43-149a-4d3d-bfa9-c069f3dfb53b.png)

**Related Items & Comparison**
![Screen Shot 2022-05-18 at 4 03 00 PM](https://user-images.githubusercontent.com/16127198/169169281-42127f56-3f20-4712-86f9-0e196303ce9d.png)

**Comment by slargman** [comment]
### [Chivichivi](https://chivichivi.com/fr/produits/t-shirt-depuis/)

**Overview**
![Screen Shot 2022-05-18 at 4 12 12 PM](https://user-images.githubusercontent.com/16127198/169170128-404f2cd3-a505-4c68-b7d7-b60cc20535bd.png)

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**
![Screen Shot 2022-05-18 at 4 12 21 PM](https://user-images.githubusercontent.com/16127198/169170131-654c8849-5fe7-4ade-a6e9-fb0d894a514f.png)

**Comment by slargman** [comment]
### [Senteurs d' Ailleurs](https://senteursdailleurs.com/gb/haute-cosmetique/154-powerbright--pure-night.html)

**Overview**
![Screen Shot 2022-05-18 at 4 14 09 PM](https://user-images.githubusercontent.com/16127198/169170259-05ad4a5a-4aa1-4e52-a457-897d1a8a224e.png)

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**
![Screen Shot 2022-05-18 at 4 14 15 PM](https://user-images.githubusercontent.com/16127198/169170268-179888c4-9f22-4b7a-ae3d-f6889deb626e.png)

**Comment by slargman** [comment]
### [Unrun](https://unrun4254.com/collections/t-shirt/products/jackie-tank-top-1)

**Overview**
![Screen Shot 2022-05-18 at 4 24 08 PM](https://user-images.githubusercontent.com/16127198/169171225-78d9158d-dba0-4598-896e-5d78471cbd3a.png)

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**

**Comment by slargman** [comment]
### [Opening Ceremony](https://www.openingceremony.com/en-us/shopping/varsityjacket-17169060)

**Overview**
![Screen Shot 2022-05-18 at 4 27 07 PM](https://user-images.githubusercontent.com/16127198/169171457-bdac5400-7359-4d94-9d0e-9ed0e7e93316.png)

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**

**Comment by slargman** [comment]
### []()

**Overview**

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**

**Comment by slargman** [comment]
### []()

**Overview**

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**

**Comment by slargman** [comment]
### []()

**Overview**

**Ratings & Reviews**

**Questions & Answers**

**Related Items & Comparison**

**Comment by slargman** [comment]
@hangyin2020 @zman811 I added some options for designs we could choose to mimic. Let me know what you think and if any jump out as you as something you would or would not like to use. We could always just use the default design

**Comment by hangyin2020** [comment]
At first, I like the Chivichivi in terms of the style. But I am thinking the red font is a little bit too much, but just like it. Then I am thinking adidas and zara are good in terms of related products, probably because I like adidas itself and zara is kind of concise and clean.

**Comment by zman811** [comment]
I like the Adidas one as well, nice that it has a reviews section to look at as most don't. I'm pretty open to any of them though

**Comment by slargman** [comment]
OK, sounds good. Let's go with adidas as our base. I also liked the red font from Chivichivi. I had concerns about accessibility though. Turns out it doesn't satisfy accessibility standards.
![Screen Shot 2022-05-19 at 11 46 58 AM](https://user-images.githubusercontent.com/16127198/169377177-f4e33088-62a7-44bd-a930-20d179d2a529.png)

**Comment by slargman** [comment]
I'll go ahead and close this issue and we can continue further design discussions in #5.
